In [12]:
from keras.models import load_model
import numpy as np 
import pandas as pd

from keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import pad_sequences

### Predicting sentiment of release of first month of chatGPT

In [11]:
df = pd.read_csv('datasets/preprocessed_chatgptfirst.csv')

In [ ]:
df = df['tweet']

In [19]:
# check if there is any NaN value

df.isnull().values.any()
df.isnull().sum()

14

In [21]:
# drop the NaN values if any

df = df.dropna()

In [22]:
df.isnull().values.any()
df.isnull().sum()

0

In [12]:
# use the pretrained model 
model = load_model('model/cnnkeras.h5', compile=False)
model.compile(optimizer="adam",
                loss='categorical_crossentropy',
                metrics=['accuracy'])

# Print the summary
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 100, 100)          11683700  
                                                                 
 conv1d (Conv1D)             (None, 99, 32)            6432      
                                                                 
 max_pooling1d (MaxPooling1D  (None, 49, 32)           0         
 )                                                               
                                                                 
 conv1d_1 (Conv1D)           (None, 48, 32)            2080      
                                                                 
 dropout (Dropout)           (None, 48, 32)            0         
                                                                 
 conv1d_2 (Conv1D)           (None, 47, 16)            1040      
                                                        

In [18]:
df.values

array(['chatgpt optimizing language models dialogue openai',
       'try talking chatgpt new optimized dialogue feedback help improve',
       'chatgpt optimizing language models dialogue machinelearning datascience artificialintelligencenntrending aiml article identified amp digested granola machinedriven rss bot ramsey elbasheer',
       ..., 'chatgpt disassembled dissemble',
       'predictions chatgpt specific trends past years nshould topic days',
       'chatgpt neat stuff'], dtype=object)

In [23]:
tokenizer = Tokenizer(num_words=50000)
tokenizer.fit_on_texts(df.values)

tweets = tokenizer.texts_to_sequences(df)

vocab_size = len(tokenizer.word_index) + 1
maxlen = 100

tweets = pad_sequences(tweets, padding='post', maxlen=maxlen)

word_index = tokenizer.word_index

In [24]:
# we have that :
# 2    positiv
# 1    neutral
# 0    negativ
pred = np.argmax(model.predict(tweets), axis=-1)

6853/6853 [==============================] - 49023s 7s/step


In [25]:
pred

array([0, 2, 2, ..., 0, 1, 1], dtype=int64)

In [26]:
len(pred)

219280

In [27]:
len(tweets)

219280

In [28]:
tweets

array([[    1,  1211,    31, ...,     0,     0,     0],
       [   72,   114,     1, ...,     0,     0,     0],
       [    1,  1211,    31, ...,     0,     0,     0],
       ...,
       [    1, 33731, 35798, ...,     0,     0,     0],
       [  944,     1,   376, ...,     0,     0,     0],
       [    1,  2018,   164, ...,     0,     0,     0]])

In [29]:
df

0         chatgpt optimizing language models dialogue op...
1         try talking chatgpt new optimized dialogue fee...
2         chatgpt optimizing language models dialogue ma...
3         thrilled share chatgpt new model optimized dia...
4         minutes ago openai released new chatgpt nnand ...
                                ...                        
219289           software projects trying replicate chatgpt
219290    asked chatgpt write nye joke seos delivered nn...
219291                       chatgpt disassembled dissemble
219292    predictions chatgpt specific trends past years...
219293                                   chatgpt neat stuff
Name: tweet, Length: 219280, dtype: object

In [30]:
len(df)

219280

In [41]:
data = df.values

In [42]:
dataframe = {'tweets': data, 'label': pred}

In [55]:
result = pd.DataFrame(dataframe)

In [56]:
result

tweets  label
0       chatgpt optimizing language models dialogue op...      0
1       try talking chatgpt new optimized dialogue fee...      2
2       chatgpt optimizing language models dialogue ma...      2
3       thrilled share chatgpt new model optimized dia...      1
4       minutes ago openai released new chatgpt nnand ...      1
...                                                   ...    ...
219275         software projects trying replicate chatgpt      0
219276  asked chatgpt write nye joke seos delivered nn...      1
219277                     chatgpt disassembled dissemble      0
219278  predictions chatgpt specific trends past years...      1
219279                                 chatgpt neat stuff      1

[219280 rows x 2 columns]

In [57]:
result.head

<bound method NDFrame.head of                                                    tweets  label
0       chatgpt optimizing language models dialogue op...      0
1       try talking chatgpt new optimized dialogue fee...      2
2       chatgpt optimizing language models dialogue ma...      2
3       thrilled share chatgpt new model optimized dia...      1
4       minutes ago openai released new chatgpt nnand ...      1
...                                                   ...    ...
219275         software projects trying replicate chatgpt      0
219276  asked chatgpt write nye joke seos delivered nn...      1
219277                     chatgpt disassembled dissemble      0
219278  predictions chatgpt specific trends past years...      1
219279                                 chatgpt neat stuff      1

[219280 rows x 2 columns]>

In [60]:
result['label'] = result['label'].replace({0: 'negativ', 1: 'neutral', 2: 'positiv'})

In [61]:
result

tweets    label
0       chatgpt optimizing language models dialogue op...  negativ
1       try talking chatgpt new optimized dialogue fee...  positiv
2       chatgpt optimizing language models dialogue ma...  positiv
3       thrilled share chatgpt new model optimized dia...  neutral
4       minutes ago openai released new chatgpt nnand ...  neutral
...                                                   ...      ...
219275         software projects trying replicate chatgpt  negativ
219276  asked chatgpt write nye joke seos delivered nn...  neutral
219277                     chatgpt disassembled dissemble  negativ
219278  predictions chatgpt specific trends past years...  neutral
219279                                 chatgpt neat stuff  neutral

[219280 rows x 2 columns]

In [62]:
result.to_csv('datasets/sentiment_chatgptfirst.csv')

### Predicting sentiment of last two months of release of chatGPT

In [63]:
df = pd.read_csv('datasets/preprocessed_chatgpt2last.csv')

In [64]:
df.head

<bound method NDFrame.head of         Unnamed: 0                                               text
0              153  fake chatgpts flood app store chatgpt appstore...
1              154  republicans release aigenerated attack preside...
2              155  sell rsi bybit recommendation short ticker zrx...
3              156  interesting chatgpt kept failing test promptge...
4              157  favourite chatgpt prompt day day act end devel...
...            ...                                                ...
188573      190488  good bad ugly typical chatgpt video chatgpt mi...
188574      190489  check new free tradingstrategy chatgpt alligat...
188575      190490                             new enemy todaychatgpt
188576      190491  cutie girl degenai altcoins altcoin degenai ge...
188577      190492  degenai amazing instant chat bot fast generate...

[188578 rows x 2 columns]>

In [65]:
# check if there is any NaN value

df.isnull().values.any()
df.isnull().sum()

Unnamed: 0    0
text          3
dtype: int64

In [66]:
# drop the NaN values if any

df = df.dropna()

In [67]:
df.isnull().values.any()
df.isnull().sum()

Unnamed: 0    0
text          0
dtype: int64

In [68]:
df.columns

Index(['Unnamed: 0', 'text'], dtype='object')

In [69]:
df = df.drop('Unnamed: 0', axis=1)

In [70]:
df.columns

Index(['text'], dtype='object')

In [71]:
df.head

<bound method NDFrame.head of                                                      text
0       fake chatgpts flood app store chatgpt appstore...
1       republicans release aigenerated attack preside...
2       sell rsi bybit recommendation short ticker zrx...
3       interesting chatgpt kept failing test promptge...
4       favourite chatgpt prompt day day act end devel...
...                                                   ...
188573  good bad ugly typical chatgpt video chatgpt mi...
188574  check new free tradingstrategy chatgpt alligat...
188575                             new enemy todaychatgpt
188576  cutie girl degenai altcoins altcoin degenai ge...
188577  degenai amazing instant chat bot fast generate...

[188575 rows x 1 columns]>

In [74]:
df.isnull().values.any()
df.isnull().sum()

text    0
dtype: int64

In [91]:
# use the pretrained model 
model = load_model('model/cnnkeras.h5', compile=False)
model.compile(optimizer="adam",
                loss='categorical_crossentropy',
                metrics=['accuracy'])

# Print the summary
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 100, 100)          11683700  
                                                                 
 conv1d (Conv1D)             (None, 99, 32)            6432      
                                                                 
 max_pooling1d (MaxPooling1D  (None, 49, 32)           0         
 )                                                               
                                                                 
 conv1d_1 (Conv1D)           (None, 48, 32)            2080      
                                                                 
 dropout (Dropout)           (None, 48, 32)            0         
                                                                 
 conv1d_2 (Conv1D)           (None, 47, 16)            1040      
                                                        

In [81]:
df.values

array([['fake chatgpts flood app store chatgpt appstore apple chatgptnews gpt artificialintelligence ainews aiupdate appstorescam applescam dailynews'],
       ['republicans release aigenerated attack president biden twiceweekly news guide tracks largelanguagemodels useful tools chatgpt bard bing update sunday'],
       ['sell rsi bybit recommendation short ticker zrxusdt minute candle price rsi powered chatgpt zrx zrx'],
       ...,
       ['new enemy todaychatgpt'],
       ['cutie girl degenai altcoins altcoin degenai gems imgnai crypto cai cryptoai chatgpt cryptocurrency'],
       ['degenai amazing instant chat bot fast generated words degenai altcoins altcoin degenai gems imgnai crypto cai cryptoai chatgpt cryptocurrency']],
      dtype=object)

In [101]:
len(df)

188575

In [89]:
len(df.values)

188575

In [87]:
temp = df.values.ravel()

In [88]:
len(temp)

188575

In [90]:
type(temp)

numpy.ndarray

In [97]:
tokenizer = Tokenizer(num_words=50000)
tokenizer.fit_on_texts(temp)

tweets = tokenizer.texts_to_sequences(df.values.ravel())

vocab_size = len(tokenizer.word_index) + 1
maxlen = 100

tweets = pad_sequences(tweets, padding='post', maxlen=maxlen)

word_index = tokenizer.word_index

In [98]:
tweets

array([[  362,   286,  6541, ...,     0,     0,     0],
       [ 8370,   514,   583, ...,     0,     0,     0],
       [  161,    19,   137, ...,     0,     0,     0],
       ...,
       [    6,  6688, 38362, ...,     0,     0,     0],
       [34872,  2281,  2122, ...,     0,     0,     0],
       [ 2122,   110,  2048, ...,     0,     0,     0]])

In [99]:
# we have that :
# 2    positiv
# 1    neutral
# 0    negativ
pred = np.argmax(model.predict(tweets), axis=-1)

5893/5893 [==============================] - 26s 4ms/step


In [100]:
pred

array([0, 2, 2, ..., 0, 1, 2], dtype=int64)

In [102]:
len(pred)

188575

In [105]:
data = df.values.ravel()

In [106]:
dataframe = {'tweets': data, 'label': pred}

In [107]:
result = pd.DataFrame(dataframe)

In [108]:
result

tweets  label
0       fake chatgpts flood app store chatgpt appstore...      0
1       republicans release aigenerated attack preside...      2
2       sell rsi bybit recommendation short ticker zrx...      2
3       interesting chatgpt kept failing test promptge...      2
4       favourite chatgpt prompt day day act end devel...      1
...                                                   ...    ...
188570  good bad ugly typical chatgpt video chatgpt mi...      1
188571  check new free tradingstrategy chatgpt alligat...      2
188572                             new enemy todaychatgpt      0
188573  cutie girl degenai altcoins altcoin degenai ge...      1
188574  degenai amazing instant chat bot fast generate...      2

[188575 rows x 2 columns]

In [109]:
result['label'] = result['label'].replace({0: 'negativ', 1: 'neutral', 2: 'positiv'})

In [110]:
result

tweets    label
0       fake chatgpts flood app store chatgpt appstore...  negativ
1       republicans release aigenerated attack preside...  positiv
2       sell rsi bybit recommendation short ticker zrx...  positiv
3       interesting chatgpt kept failing test promptge...  positiv
4       favourite chatgpt prompt day day act end devel...  neutral
...                                                   ...      ...
188570  good bad ugly typical chatgpt video chatgpt mi...  neutral
188571  check new free tradingstrategy chatgpt alligat...  positiv
188572                             new enemy todaychatgpt  negativ
188573  cutie girl degenai altcoins altcoin degenai ge...  neutral
188574  degenai amazing instant chat bot fast generate...  positiv

[188575 rows x 2 columns]

In [111]:
result.to_csv('datasets/sentiment_chatgpt2last.csv')

### Predicting the whole dataset of chatGPT

In [42]:
df = pd.read_csv('datasets/preprocessed_chatgpt.csv', usecols=['text','user_description','date'])

In [43]:
df.head()

user_description  \
0  building draftmateai developer author chatgpt ...   
1  nomadic marketing vigilante graphic web design...   
2  leading translation management platform locali...   
3  engineering leader coach mentor building remot...   
4  stop learning research develop uild future eyo...   

                                                text  \
0  happy share draftmateai support day free trial...   
1  integrate chatgpt marketo smart campaign disco...   
2  pleased announce new patentpending technology ...   
3  starting tire scolded chatgpt slight perceived...   
4  spartajustice it notable wikipedia entry john ...   

                        date  
0  2023-04-26 13:02:16+00:00  
1  2023-04-26 13:02:06+00:00  
2  2023-04-26 13:02:05+00:00  
3  2023-04-26 13:02:00+00:00  
4  2023-04-26 13:01:52+00:00

In [44]:
len(df)

374777

In [46]:
df.isnull().values.any()
df.isnull().sum()

user_description    5504
text                   4
date                   0
dtype: int64

In [47]:
df = df.dropna()

In [48]:
df.isnull().values.any()
df.isnull().sum()

user_description    0
text                0
date                0
dtype: int64

In [49]:
# use the pretrained model 
model = load_model('model/cnnkeras.h5', compile=False)
model.compile(optimizer="adam",
                loss='categorical_crossentropy',
                metrics=['accuracy'])

# Print the summary
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 100, 100)          11683700  
                                                                 
 conv1d (Conv1D)             (None, 99, 32)            6432      
                                                                 
 max_pooling1d (MaxPooling1D  (None, 49, 32)           0         
 )                                                               
                                                                 
 conv1d_1 (Conv1D)           (None, 48, 32)            2080      
                                                                 
 dropout (Dropout)           (None, 48, 32)            0         
                                                                 
 conv1d_2 (Conv1D)           (None, 47, 16)            1040      
                                                        

In [50]:
df.text

0         happy share draftmateai support day free trial...
1         integrate chatgpt marketo smart campaign disco...
2         pleased announce new patentpending technology ...
3         starting tire scolded chatgpt slight perceived...
4         spartajustice it notable wikipedia entry john ...
                                ...                        
374772    chatgpt biggest smartest brain world right now...
374773    levelsso happy chatgpt team com revolutionary ...
374774    russel chatgpt it funny take long time answer ...
374775    wondering difference jasper chatgpt gpt chatgp...
374776    chatgpt similar llm pose challenge academic in...
Name: text, Length: 369270, dtype: object

In [51]:
temp = df.text.values

In [52]:
tokenizer = Tokenizer(num_words=50000)
tokenizer.fit_on_texts(temp)

tweets = tokenizer.texts_to_sequences(df.text.values)

vocab_size = len(tokenizer.word_index) + 1
maxlen = 100

tweets = pad_sequences(tweets, padding='post', maxlen=maxlen)

word_index = tokenizer.word_index

In [53]:
tweets

array([[  499,   149,   304, ...,     0,     0,     0],
       [  677,     1, 24365, ...,     0,     0,     0],
       [ 4827,  1733,     7, ...,     0,     0,     0],
       ...,
       [40786,     1,    13, ...,     0,     0,     0],
       [ 1133,   703,  2396, ...,     0,     0,     0],
       [    1,   480,   130, ...,     0,     0,     0]])

In [54]:
word_index

{'chatgpt': 1,
 'openai': 2,
 'gpt': 3,
 'artificialintelligence': 4,
 'like': 5,
 'google': 6,
 'new': 7,
 'use': 8,
 'technology': 9,
 'amp': 10,
 'time': 11,
 'tool': 12,
 'it': 13,
 'future': 14,
 'chatbot': 15,
 'tech': 16,
 'prompt': 17,
 'know': 18,
 'microsoft': 19,
 'asked': 20,
 'nft': 21,
 'way': 22,
 'world': 23,
 'chat': 24,
 'help': 25,
 'write': 26,
 'business': 27,
 'check': 28,
 'human': 29,
 'question': 30,
 'answer': 31,
 'model': 32,
 'work': 33,
 'web': 34,
 'language': 35,
 'data': 36,
 'resume': 37,
 'think': 38,
 'need': 39,
 'bing': 40,
 'content': 41,
 'crypto': 42,
 'here': 43,
 'people': 44,
 'search': 45,
 'good': 46,
 'bard': 47,
 'day': 48,
 'code': 49,
 'read': 50,
 'today': 51,
 'create': 52,
 'now': 53,
 'midjourney': 54,
 'machinelearning': 55,
 'intelligence': 56,
 'want': 57,
 'job': 58,
 'learn': 59,
 'free': 60,
 'thing': 61,
 'short': 62,
 'let': 63,
 'better': 64,
 'writing': 65,
 'news': 66,
 'dont': 67,
 'elonmusk': 68,
 'long': 69,
 'user': 7

In [55]:
pred = np.argmax(model.predict(tweets), axis=-1)

11540/11540 [==============================] - 142s 12ms/step


In [56]:
pred

array([2, 2, 2, ..., 1, 2, 2], dtype=int64)

In [57]:
len(pred)

369270

In [58]:
pred_series = pd.Series(pred)

In [59]:
len(pred_series)

369270

In [60]:
len(df.text)

369270

In [69]:
dataframe = {'user_description': df.user_description.values, 'tweets': df.text.values, 'label': pred, 'date': df.date.values}

In [70]:
result = pd.DataFrame(dataframe)

In [71]:
result

user_description  \
0       building draftmateai developer author chatgpt ...   
1       nomadic marketing vigilante graphic web design...   
2       leading translation management platform locali...   
3       engineering leader coach mentor building remot...   
4       stop learning research develop uild future eyo...   
...                                                   ...   
369265  brain meant processing million tweet post vide...   
369266  blockchain enthusiast philanthropist slave jav...   
369267  mathematician developer amazon previously geob...   
369268    passionate nature software developer profession   
369269  postdoc gipplab unigoettingen phd unikonstanz ...   

                                                   tweets  label  \
0       happy share draftmateai support day free trial...      2   
1       integrate chatgpt marketo smart campaign disco...      2   
2       pleased announce new patentpending technology ...      2   
3       starting tire scolded chatgpt slight perceived...      1   
4       spartajustice it notable wikipedia entry john ...      2   
...                                                   ...    ...   
369265  chatgpt biggest smartest brain world right now...      0   
369266  levelsso happy chatgpt team com revolutionary ...      2   
369267  russel chatgpt it funny take long time answer ...      1   
369268  wondering difference jasper chatgpt gpt chatgp...      2   
369269  chatgpt similar llm pose challenge academic in...      2   

                             date  
0       2023-04-26 13:02:16+00:00  
1       2023-04-26 13:02:06+00:00  
2       2023-04-26 13:02:05+00:00  
3       2023-04-26 13:02:00+00:00  
4       2023-04-26 13:01:52+00:00  
...                           ...  
369265  2022-12-05 17:11:10+00:00  
369266  2022-12-05 17:10:31+00:00  
369267  2022-12-05 17:09:04+00:00  
369268  2022-12-05 17:08:44+00:00  
369269  2022-12-05 17:08:20+00:00  

[369270 rows x 4 columns]

In [72]:
result['label'] = result['label'].replace({0: 'negativ', 1: 'neutral', 2: 'positiv'})

In [73]:
result

user_description  \
0       building draftmateai developer author chatgpt ...   
1       nomadic marketing vigilante graphic web design...   
2       leading translation management platform locali...   
3       engineering leader coach mentor building remot...   
4       stop learning research develop uild future eyo...   
...                                                   ...   
369265  brain meant processing million tweet post vide...   
369266  blockchain enthusiast philanthropist slave jav...   
369267  mathematician developer amazon previously geob...   
369268    passionate nature software developer profession   
369269  postdoc gipplab unigoettingen phd unikonstanz ...   

                                                   tweets    label  \
0       happy share draftmateai support day free trial...  positiv   
1       integrate chatgpt marketo smart campaign disco...  positiv   
2       pleased announce new patentpending technology ...  positiv   
3       starting tire scolded chatgpt slight perceived...  neutral   
4       spartajustice it notable wikipedia entry john ...  positiv   
...                                                   ...      ...   
369265  chatgpt biggest smartest brain world right now...  negativ   
369266  levelsso happy chatgpt team com revolutionary ...  positiv   
369267  russel chatgpt it funny take long time answer ...  neutral   
369268  wondering difference jasper chatgpt gpt chatgp...  positiv   
369269  chatgpt similar llm pose challenge academic in...  positiv   

                             date  
0       2023-04-26 13:02:16+00:00  
1       2023-04-26 13:02:06+00:00  
2       2023-04-26 13:02:05+00:00  
3       2023-04-26 13:02:00+00:00  
4       2023-04-26 13:01:52+00:00  
...                           ...  
369265  2022-12-05 17:11:10+00:00  
369266  2022-12-05 17:10:31+00:00  
369267  2022-12-05 17:09:04+00:00  
369268  2022-12-05 17:08:44+00:00  
369269  2022-12-05 17:08:20+00:00  

[369270 rows x 4 columns]

In [74]:
result.to_csv('datasets/sentiment_chatgpt.csv')